### ISSUE TITLE
property `creeps` Property not found in statics of Memory

### ISSUE THREAD

**Issue by erinpentecost** [FossiFoo/screeps-flowtype#2]
Any ideas on how  to fix warnings for Memory.creeps and other related uses?

property `creeps` Property not found in statics of Memory

**Comment by FossiFoo** [comment]
Oh, sorry I didn't see this earlier. I use my own definition of Memory and typecast before accessing it. Since Memory will always be structured differently it's only possible to have it as any or such I guess.
